Repository AdarshaHalder/HacktoberFest--2022, pull requests merged in 2022-10, with the labels that each got.

#7 Commiting on knapsack .
  KnapsackU.java
Labels: help wanted, hacktober-fest 2022, hacktober-fest, hacktober-fest accepted, Hacktoberfest-2022, Hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#8 Non-prime number between a range in shell script
  Non-prime number between a range in shell script
Labels: hacktober-fest 2022, hacktober-fest, hacktober-fest accepted, Hacktoberfest-2022, Hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#10 Non-prime number between a range in shell script
  Non-prime number between a range in shell script
Labels: enhancement, hacktober-fest 2022, hacktober-fest, hacktober-fest accepted, Hacktoberfest-2022, Hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#14 Saddle point
  Saddle point
Labels: enhancement, question, hacktober-fest 2022, hacktober-fest, hacktober-fest accepted, Hacktoberfest-2022, Hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#15 Sieve of Eratosthenes Commit
  Prime.java
Labels: enhancement, hacktober-fest 2022, hacktober-fest, hacktober-fest accepted, Hacktoberfest-2022, Hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#19 Goldbach-conjecture, 1 commit ahead.
  Untitled-5.c
Labels: enhancement, question, hacktober-fest 2022, hacktober-fest, hacktober-fest accepted, Hacktoberfest-2022, Hacktoberfest-accepted, hacktoberfest2022, hacktoberfest
